# Site configuration
favicon = "images/logo-v10-favicon.png"
logo = "images/logo-v10.png"
logo_darkmode = "images/logo-v10-dark.png"
logo_width = "160px"
logo_height = "32px"
logo_webp = true
logo_text = "Te Moana Mahana"

# Navigation
navbar_fixed = true

# Theme
theme_switcher = true
theme_default = "system"
mainSections = ["blog"]

# External services
contact_form_action = "#"
google_tag_manager = ""
google_adsense = ""
custom_script = ""

# Copyright
copyright = "Designed and Developed by Te Moana Mahana"

# Preloader
[preloader]
enable = false
preloader = ""

# CTA Button
[navigation_button]
enable = false
label = "get a quote"
link = "contact"

# Search
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog", "authors"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# Announcement bar
[announcement]
enable = false
expire_days = 31
content = "<span class='text-center block'>**Announcing the launch of our new website!** <a class='underline' href='/updates/' target='_blank' rel='noopener'>Read more</a></span>"

# SEO metadata
[metadata]
keywords = []
description = "Te Moana Mahana"
author = "TeMoMa"
image = "images/og-image.png"

# Site verification
[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""
mastodon = ""

# Cookie consent
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# Diagrams
[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

# Sidebar widgets
[widgets]
sidebar = ["categories", "tags"]

# Google Maps
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# Mailing list
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
